version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD}
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
        consistency: delegated
    init: true
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G