services:
  web:
    build: .
    image: github-issue-similarity:latest
    container_name: github-issue-similarity
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD}
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
        consistency: delegated
      - type: volume
        source: model-cache
        target: /cache
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  model-cache: